# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oFN7cuk89UDyLq0hyqT-0KFUfBepcPcL
"""

#Se crea un ciclo que toma valores desde 1 hasta 11-1.
for i in range(1,11):
  #Se imprime la serie de unos con el truco indicado.
  print(i*"1")